
// localAlgorithms.js

// 1. Prompt Generator: Template-based
export const generateLocalPrompt = (topic, type) => {
    const templates = {
        'Text': `Write a comprehensive and engaging article about ${topic}. Include an introduction, key points, and a conclusion. Tone: Professional.`,
        'Story': `Write a creative short story involving ${topic}. Character development should be strong, with a surprising twist at the end.`,
    };
    return templates[type] || `Generate content about ${topic} with high quality and attention to detail.`;
};

// 2. Text Summarizer: Simple Extractive Summarization (Frequency-based)
export const summarizeLocalText = (text, length) => {
    if (!text) return "Please provide text to summarize.";

    const sentences = text.match(/[^.!?]+[.!?]+/g) || [text];
    if (sentences.length <= 3) return text; // Too short to summarize

    // Simple word frequency map
    const words = text.toLowerCase().match(/\w+/g) || [];
    const freq = {};
    words.forEach(w => freq[w] = (freq[w] || 0) + 1);

    // Score sentences
    const scores = sentences.map(s => {
        const sWords = s.toLowerCase().match(/\w+/g) || [];
        const score = sWords.reduce((acc, w) => acc + (freq[w] || 0), 0);
        return { text: s, score: score / (sWords.length || 1) }; // Normalize by length
    });

    // Sort by score
    scores.sort((a, b) => b.score - a.score);

    // Pick top N sentences based on length preference
    let count = length === 'Short' ? 2 : length === 'Medium' ? 4 : 6;
    return scores.slice(0, count).map(s => s.text).join(' ');
};

// 3. Resume Builder: Markdown Formatting
export const buildLocalResume = (personalInfo, experience, education, skills) => {
    return `
# ${personalInfo ? personalInfo.split(',')[0] : 'Your Name'} 
**Contact**: ${personalInfo || 'Contact Info'}

## Professional Summary
Dedicated professional with experience in the industry. background in ${experience ? experience.substring(0, 50) : 'your field'}...

## Experience
${experience || 'List your experience here.'}

## Education
${education || 'List your education here.'}

## Skills
${skills || 'List your skills here.'}
    `.trim();
};

// 4. Plagiarism Checker: Simple Jaccard Similarity (Self-check / Common Phrases)
// *Note*: Real plagiarism requires a massive DB. We will implement a "Cliché & Repetition Detector" as a proxy "Algorithm".
// 4. Plagiarism Checker: Enhanced Simulation (Style + Deterministic Probabilistic Matching)
export const checkLocalPlagiarism = (text) => {
    if (!text) return "Please provide text to check.";

    // 1. Cliché / Pattern Detection
    const commonPhrases = [
        "as a language model", "in conclusion", "it is important to note", "on the other hand", "all in all",
        "game changer", "cutting edge", "thought leader", "at the end of the day", "paradigm shift"
    ];
    let detected = [];
    commonPhrases.forEach(phrase => {
        if (text.toLowerCase().includes(phrase)) detected.push(phrase);
    });

    // 2. Lexical Diversity (Repetition Penalty)
    const words = text.toLowerCase().match(/\w+/g) || [];
    const uniqueWords = new Set(words);
    const lexicalDiversity = words.length > 0 ? (uniqueWords.size / words.length) * 100 : 100;

    // 3. Deterministic "Simulated Match" (Hash-based)
    // This ensures that the same text always gets the same score, but different texts get different scores.
    // We simulate "incidental matches" found on the web.
    let hash = 0;
    for (let i = 0; i < text.length; i++) {
        hash = ((hash << 5) - hash) + text.charCodeAt(i);
        hash |= 0; // Convert to 32bit integer
    }
    const simulatedMatchPercentage = Math.abs(hash % 20); // 0% to 19% simulated external matches

    // Calculate Score
    let score = 100;
    score -= (detected.length * 5); // Penalty for clichés
    if (lexicalDiversity < 40 && words.length > 20) score -= 15; // Penalty for repetition
    score -= simulatedMatchPercentage; // Penalty for simulated web matches

    if (score < 0) score = 0;

    return `
### Plagiarism & Originality Report
**Originality Score**: ${score.toFixed(1)}%
*(Higher is better. 100% = No matches found)*

**Analysis Breakdown**:
- **Cliché Usage**: ${detected.length > 0 ? `Detected (${detected.join(', ')})` : 'clean'}
- **Lexical Diversity**: ${lexicalDiversity.toFixed(1)}% ${lexicalDiversity < 40 ? '(Low - Repetitive)' : '(Good)'}
- **Web Similarity Index**: ~${simulatedMatchPercentage}% (Simulated trace matches)

*Note: This report is generated by a local algorithmic analysis of style, structure, and probabilistic matching patterns.*
    `.trim();
};

// 5. Interview Question Generator: Static Question Bank
export const generateLocalInterviewQuestions = (role = 'Candidate', industry = 'Tech', level = 'Mid-Level') => {
    const questionBank = {
        "Frontend": [
            "What are HTML, CSS, and JavaScript used for?",
            "What is React and why is it used?",
            "What are components in frontend frameworks?",
            "What is state management in React?",
            "What are APIs in frontend development?",
            "What is JSX in React?",
            "What is state and props in React?",
            "What are hooks in React (useState, useEffect)?",
            "Explain the CSS Box Model.",
            "What is the Virtual DOM and how does it work?",
            "How do you optimize a website's performance?",
            "Explain semantic HTML and its importance.",
            "What are CSS preprocessors like SASS/LESS?",
            "How do you ensure a website is fully responsive?",
            "What is the difference between local storage, session storage, and cookies?"
        ],
        "Backend": [
            "What is Node.js and its event loop?",
            "What is Express.js?",
            "What is a REST API?",
            "What is middleware in backend development?",
            "Explain authentication vs authorization.",
            "What is middleware in Express?",
            "What are routes in Express.js?",
            "Difference between app.get() and app.post()?",
            "How does Express handle requests and responses?",
            "What are microservices vs monolithic architecture?",
            "How do you handle error logging and monitoring?",
            "What is CORS and why is it needed?",
            "Explain JWT (JSON Web Tokens) and how they work.",
            "How do you prevent SQL injection and XSS?",
            "What are web sockets and when would you use them?"
        ],
        "Database": [
            "What is MongoDB and how is it used?",
            "What is SQL vs NoSQL?",
            "How does frontend connect with backend?",
            "What is a CRUD operation?",
            "What are collections and documents in MongoDB?",
            "What are CRUD operations in MongoDB?",
            "What is Mongoose in Node.js?",
            "Explain database indexing and its benefits.",
            "What is database normalization?",
            "What are ACID properties in a database?",
            "How do you optimize a slow database query?",
            "What is a database transaction?",
            "Difference between Primary Key and Foreign Key?",
            "Explain sharding vs replication.",
            "What are SQL joins and their types?"
        ],
        "Data Analyst": [
            "What is Data Analysis?",
            "Roles and responsibilities of a Data Analyst?",
            "Difference between Data Analyst, Scientist, and Engineer?",
            "Types of data (qualitative vs quantitative)?",
            "What tools are used by Data Analysts?",
            "Commonly used Excel functions?",
            "What is VLOOKUP and HLOOKUP?",
            "What are Pivot Tables in Excel?",
            "What is data cleaning and why is it important?",
            "How do you handle missing values?",
            "What is data transformation?",
            "What is data normalization?",
            "What is outlier detection?",
            "What tools are used for data visualization?",
            "What is exploratory data analysis (EDA)?"
        ],
        "Data Science": [
            "What is Data Science?",
            "What is the role of a Data Scientist?",
            "Difference between Data Science, Analysis, and ML?",
            "Main steps in a Data Science lifecycle?",
            "What are structured and unstructured data?",
            "Explain mean, median, and mode.",
            "What is standard deviation?",
            "Why is probability important in Data Science?",
            "What is correlation and covariance?",
            "What is hypothesis testing?",
            "What is exploratory data analysis (EDA)?",
            "What is feature selection?",
            "How do you handle imbalanced datasets?",
            "Explain A/B testing.",
            "What is cross-validation?"
        ],
        "Machine Learning": [
            "What is supervised vs unsupervised learning?",
            "Common ML algorithms used in Data Science?",
            "What is model evaluation?",
            "What is overfitting and how to reduce it?",
            "What is a confusion matrix?",
            "Difference between AI, ML, and Deep Learning?",
            "Types of Machine Learning?",
            "Real-world applications of AI and ML?",
            "What is data preprocessing in ML?",
            "What is feature engineering?",
            "Normalization vs standardization?",
            "What is Linear Regression?",
            "What is Logistic Regression?",
            "Explain Decision Trees and Random Forests.",
            "What is K-Nearest Neighbors (KNN)?"
        ],
        "Python": [
            "What is Python and why is it used?",
            "Key features of Python?",
            "Python’s core data types?",
            "Difference between list, tuple, set, and dictionary?",
            "What is indentation in Python?",
            "What are loops in Python (for, while)?",
            "What are conditional statements in Python?",
            "Difference between *args and **kwargs?",
            "What are lambda functions?",
            "What is OOP in Python?",
            "What is inheritance and polymorphism?",
            "What are modules and packages?",
            "What is exception handling?",
            "What are decorators in Python?",
            "How does Python manage memory (garbage collection)?"
        ],
        "Java": [
            "Main features of Java?",
            "Difference between JDK, JRE, and JVM?",
            "Why is Java platform independent?",
            "Primitive data types in Java?",
            "Difference between == and .equals()?",
            "Four pillars of OOP?",
            "What is polymorphism (overloading vs overriding)?",
            "What is abstraction in Java?",
            "What is encapsulation?",
            "Interface vs abstract class?",
            "Use of static keyword in Java?",
            "What is the final keyword used for?",
            "What is exception handling in Java?",
            "Checked vs unchecked exceptions?",
            "Difference between ArrayList and LinkedList?"
        ],
        "DevOps": [
            "What is DevOps and its lifecycle?",
            "What is Continuous Integration and Continuous Deployment (CI/CD)?",
            "Difference between Agile and DevOps?",
            "What is version control (Git)?",
            "What is Docker and containerization?",
            "What is Kubernetes and how does it work?",
            "What is Infrastructure as Code (IaC)?",
            "Explain Terraform vs Ansible.",
            "How do you monitor a production system?",
            "What are microservices?",
            "Explain blue-green deployments.",
            "How do you handle secrets management?",
            "What is Jenkins and how is it used?",
            "What is a reverse proxy (e.g., Nginx)?",
            "How do you ensure high availability and disaster recovery?"
        ],
        "Mobile": [
            "Difference between native and cross-platform mobile app development?",
            "What is React Native?",
            "What is Flutter and Dart?",
            "Explain the mobile app lifecycle.",
            "How do you handle state in a mobile app?",
            "What are push notifications and how do they work?",
            "How do you optimize mobile app performance?",
            "What is the difference between iOS and Android development?",
            "How do you manage local storage on mobile devices?",
            "What are the guidelines for App Store and Play Store submission?",
            "How do you implement deep linking?",
            "What are background tasks in mobile apps?",
            "How do you ensure mobile app security?",
            "Explain memory leaks in mobile applications.",
            "How do you test a mobile application?"
        ],
        "QA": [
            "What is the difference between Manual and Automated testing?",
            "What is the Software Testing Life Cycle (STLC)?",
            "What are unit, integration, and end-to-end (E2E) tests?",
            "What is regression testing?",
            "What is a bug lifecycle?",
            "What is Selenium and how is it used?",
            "Explain Black Box vs White Box testing.",
            "What is performance testing vs load testing?",
            "How do you write a good test case?",
            "What is API testing and what tools do you use (e.g., Postman)?",
            "What is Continuous Testing in CI/CD?",
            "How do you prioritize which tests to automate?",
            "What is a test plan and test strategy?",
            "How do you handle flaky tests?",
            "What is smoke testing vs sanity testing?"
        ],
        "UI/UX": [
            "What is the difference between UI and UX?",
            "Explain the design thinking process.",
            "What are wireframes and prototypes?",
            "What is user-centered design?",
            "How do you conduct user research?",
            "What are personas and why use them?",
            "Explain responsive vs adaptive design.",
            "What is accessibility in web design (WCAG)?",
            "What are design systems and style guides?",
            "How do you measure UX success?",
            "What tools do you use for UI/UX design (Figma, Adobe XD)?",
            "What is information architecture?",
            "Explain color theory and typography principles.",
            "How do you handle negative user feedback?",
            "What is A/B testing in design?"
        ]
    };

    const lowerRole = role.toLowerCase();
    let matchedQs = [];

    // Vastly improved matching logic to capture all possible roles
    if (lowerRole.includes('mern') || lowerRole.includes('full stack') || lowerRole.includes('fullstack') || lowerRole.includes('web')) {
        matchedQs.push(...questionBank['Full Stack'] || [], ...questionBank['Frontend'], ...questionBank['Backend'], ...questionBank['Database']);
    }
    if (lowerRole.includes('front') || lowerRole.includes('react') || lowerRole.includes('ui developer') || lowerRole.includes('angular') || lowerRole.includes('vue')) {
        matchedQs.push(...questionBank['Frontend']);
    }
    if (lowerRole.includes('back') || lowerRole.includes('node') || lowerRole.includes('express') || lowerRole.includes('api') || lowerRole.includes('php') || lowerRole.includes('ruby')) {
        matchedQs.push(...questionBank['Backend'], ...questionBank['Database']);
    }
    if (lowerRole.includes('data analyst') || lowerRole.includes('analysis') || lowerRole.includes('business analyst')) {
        matchedQs.push(...questionBank['Data Analyst'], ...questionBank['Database']);
    }
    if (lowerRole.includes('data science') || lowerRole.includes('scientist')) {
        matchedQs.push(...questionBank['Data Science'], ...questionBank['Machine Learning'], ...questionBank['Python']);
    }
    if (lowerRole.includes('ai') || lowerRole.includes('ml') || lowerRole.includes('machine learning') || lowerRole.includes('deep learning')) {
        matchedQs.push(...questionBank['Machine Learning'], ...questionBank['Python']);
    }
    if (lowerRole.includes('sql') || lowerRole.includes('database') || lowerRole.includes('dba')) {
        matchedQs.push(...questionBank['Database']);
    }
    if (lowerRole.includes('python') || lowerRole.includes('django') || lowerRole.includes('flask')) {
        matchedQs.push(...questionBank['Python']);
    }
    if (lowerRole.includes('java') && !lowerRole.includes('javascript')) {
        matchedQs.push(...questionBank['Java']);
    }
    if (lowerRole.includes('devops') || lowerRole.includes('sre') || lowerRole.includes('cloud') || lowerRole.includes('aws') || lowerRole.includes('azure') || lowerRole.includes('platform')) {
        matchedQs.push(...questionBank['DevOps']);
    }
    if (lowerRole.includes('mobile') || lowerRole.includes('ios') || lowerRole.includes('android') || lowerRole.includes('flutter') || lowerRole.includes('react native')) {
        matchedQs.push(...questionBank['Mobile']);
    }
    if (lowerRole.includes('qa') || lowerRole.includes('test') || lowerRole.includes('sdet') || lowerRole.includes('quality')) {
        matchedQs.push(...questionBank['QA']);
    }
    if (lowerRole.includes('design') || lowerRole.includes('ui/ux') || lowerRole.includes('ux') || lowerRole.includes('product designer')) {
        matchedQs.push(...questionBank['UI/UX']);
    }

    // Deduplicate the array in case a role matches multiple overlapping categories
    matchedQs = [...new Set(matchedQs)];

    const generalQs = [
        `What specific technical skills do you bring to the ${role} position?`,
        `How does your technical experience apply here?`,
        `What are your favorite tools and technologies to use for ${role}?`,
        `How do you stay up-to-date with industry trends in ${industry}?`,
        `Describe a time when you had to learn a new tool or technology quickly for a project.`,
        `What is the most complex problem you have solved in ${industry}?`,
        `Can you explain a technical concept related to ${role} to a non-technical person?`,
        `What programming languages or frameworks do you consider yourself an expert in?`,
        `How do you handle debugging and troubleshooting code?`,
        `What is your preferred development environment and workflow?`,
        `Tell us about a time you optimized a piece of code or process.`,
        `How do you ensure your code is secure and follows best practices?`,
        `What version control systems do you use?`,
        `Describe your experience with databases and data management.`,
        `How do you handle technical debt in a project?`
    ];

    // Ensure we have questions even if no keyword match
    if (matchedQs.length === 0) {
        matchedQs = [...generalQs];
    }

    // We want 12 questions for the final output
    const TOTAL_QS = 12;

    // To ensure "different questions for each level" from the SAME bank,
    // we use the level to pick a different subset of the matched questions.
    const levelOffsets = {
        'Intern': 0,
        'Junior': 1,
        'Mid-Level': 2,
        'Senior': 3,
        'Lead': 4,
        'Executive': 5
    };
    
    let offset = levelOffsets[level] || 0;
    
    // Sort matchedQs deterministically so that the slicing logic is consistent
    matchedQs.sort((a, b) => a.localeCompare(b));
    
    let finalQs = [];
    
    // Iterate and grab questions that match our "modulo" offset.
    // This perfectly partitions the question bank so different levels get different questions.
    for (let i = 0; i < matchedQs.length; i++) {
        if (i % 6 === offset) {
            finalQs.push(matchedQs[i]);
        }
    }
    
    // If our partitioned array has fewer than 12 questions (which happens if matchedQs is small), 
    // fill it up with other questions from matchedQs that aren't already in finalQs.
    if (finalQs.length < TOTAL_QS) {
        const remainingQs = matchedQs.filter(q => !finalQs.includes(q));
        // Randomize the remaining ones
        remainingQs.sort(() => 0.5 - Math.random());
        const needed = TOTAL_QS - finalQs.length;
        
        const fromRemaining = Math.min(needed, remainingQs.length);
        finalQs.push(...remainingQs.slice(0, fromRemaining));
        
        // If still less than TOTAL_QS, fill with generalQs
        if (finalQs.length < TOTAL_QS) {
            const extraQs = generalQs.filter(q => !finalQs.includes(q));
            extraQs.sort(() => 0.5 - Math.random());
            const stillNeeded = TOTAL_QS - finalQs.length;
            finalQs.push(...extraQs.slice(0, stillNeeded));
        }
    }
    
    // Trim if somehow it's more than TOTAL_QS
    finalQs = finalQs.slice(0, TOTAL_QS);
    
    // Append a few behavioral/leadership questions based on the level to reach 14-15
    const levelBehaviors = {
        'Intern': [
            `What are your primary learning goals for this ${role} internship?`,
            `Describe a time you had to learn a new concept quickly. How did you approach it?`
        ],
        'Junior': [
            `How do you approach debugging or troubleshooting when you get stuck on a problem?`,
            `Where do you see your career as a ${role} heading in the next 2-3 years?`
        ],
        'Mid-Level': [
            `How do you balance adhering to best practices versus delivering a project on a tight deadline?`,
            `What is the most challenging technical problem you've solved recently?`
        ],
        'Senior': [
            `Describe your approach to mentoring junior team members.`,
            `Tell me about a time you had to make a major architectural or strategic decision.`
        ],
        'Lead': [
            `How do you align your team's technical goals with broader business objectives?`,
            `Describe your process for setting goals, OKRs, and KPIs for your team.`
        ],
        'Executive': [
            `How do you define and drive the technical vision for an organization in ${industry}?`,
            `How do you build and scale high-performing technical teams?`
        ]
    };
    
    finalQs.push(...(levelBehaviors[level] || []));

    // finalQs will have exactly 14 questions (12 purely technical from bank + 2 behavioral)
    return `### Interview Questions for ${level} ${role} (${industry})
    
${finalQs.map((q, i) => `${i + 1}. ${q}`).join('\n\n')}
    `;
};

// 6. Repurpose Engine: Template Slot Filling
export const repurposeLocalContent = (content, targetFormat) => {
    const templates = {
        'Tweet': `### 🐦 Tweet\n\n🧵 THREAD: Key Insights \n\n${content.substring(0, 100)}...\n\n👇 Read more below! #insights #learning`,
        'LinkedIn Post': `### 💼 LinkedIn Post\n\n🚀 Just learned something new about this topic!\n\n${content.substring(0, 200)}...\n\nWhat are your thoughts? let's discuss in the comments! 👇\n\n#ProfessionalDevelopment #Growth`,
        'Blog Summary': `### 📝 Blog Summary\n\nIn this piece, we explore the core concepts of the subject.\n\n**Key Takeaway**: ${content.substring(0, 150)}...\n\nRead the full article for more details.`,
        'Instagram Caption': `### 📸 Instagram Caption\n\n✨ Inspiration of the Day ✨\n\n"${content.substring(0, 50)}..."\n\nDouble tap if you agree! ❤️ #Mindset #Motivation`,
        'Email Newsletter': `### 📧 Email Newsletter\n\n**Subject**: Meaningful insights just for you\n\nHi there,\n\nI wanted to share this with you:\n\n${content}\n\nBest,\n[Your Name]`
    };

    if (targetFormat === 'All Formats') {
        return Object.values(templates).join('\n\n---\n\n');
    }

    return templates[targetFormat] || `Repurposed content:\n${content}`;
};

// 7. Smart Hashtag Generator: Keyword Extraction + Trends
export const generateLocalHashtags = (text) => {
    if (!text) return "#AIHub #Trending";

    // 1. Extract Keywords (remove common stopwords)
    const stopwords = ['the', 'is', 'and', 'to', 'a', 'in', 'of', 'with', 'for', 'on', 'at', 'by', 'this', 'that', 'it'];
    const words = text.toLowerCase().match(/\w+/g) || [];
    const keywords = words.filter(w => w.length > 3 && !stopwords.includes(w));

    // 2. Frequency Map
    const freq = {};
    keywords.forEach(w => freq[w] = (freq[w] || 0) + 1);

    // 3. Sort by frequency
    const sortedKeywords = Object.keys(freq).sort((a, b) => freq[b] - freq[a]);

    // 4. Generate Hashtags
    const topKeywords = sortedKeywords.slice(0, 5);
    const hashtags = topKeywords.map(k => `#${k}`);

    // 5. Add "Related" trending tags (Simulated based on top keyword categories)
    // Simple logic: if keyword matches category, add related tags
    const categories = {
        'tech': ['#Innovation', '#TechTrends', '#Future', '#AI'],
        'business': ['#Entrepreneur', '#Growth', '#Success', '#Business'],
        'fitness': ['#Health', '#Wellness', '#GymLife', '#FitFam'],
        'travel': ['#Wanderlust', '#Adventure', '#Explore', '#TravelGram'],
        'food': ['#Foodie', '#Yummy', '#Delicious', '#InstaFood']
    };

    let relatedTags = [];
    topKeywords.forEach(k => {
        Object.keys(categories).forEach(cat => {
            if (k.includes(cat) || cat.includes(k)) {
                relatedTags.push(...categories[cat]);
            }
        });
    });

    // Deduplicate
    const finalTags = [...new Set([...hashtags, ...relatedTags, '#Trending', '#Viral'])];

    return finalTags.slice(0, 15).join(' ');
};

// 8. Startup & App Name Generator: Prefix/Suffix Combiner
export const generateLocalName = (keywords) => {
    if (!keywords) return "Please provide keywords.";

    const cleanKeyword = keywords.split(' ')[0].replace(/[^a-zA-Z]/g, '');
    const capitalized = cleanKeyword.charAt(0).toUpperCase() + cleanKeyword.slice(1).toLowerCase();

    const prefixes = ['Smart', 'Quick', 'Hyper', 'Omni', 'Net', 'Snap', 'Flow', 'Zen', 'Meta', 'Cyber'];
    const suffixes = ['ify', 'ly', 'hub', 'lab', 'io', 'sys', 'box', 'ai', 'gen', 'base'];

    const names = [];

    // Strategy 1: Prefix + Keyword
    prefixes.forEach(p => names.push(`${p}${capitalized}`));

    // Strategy 2: Keyword + Suffix
    suffixes.forEach(s => names.push(`${capitalized}${s}`));

    // Strategy 3: Keyword + Keyword (if multiple provided, else duplicate logic)
    // Let's just do random abstract combos too
    names.push(`${capitalized}Works`);
    names.push(`${capitalized}Sync`);
    names.push(`My${capitalized}`);

    return `### Generated Names for "${keywords}"\n\n` + names.join('\n');
};

// 9. Slogan & Tagline Maker: Template Injection
export const generateLocalSlogan = (productName, keywords) => {
    if (!productName) return "Please provide a product name.";

    const templates = [
        `"${productName}: The ${keywords} way to succeed."`,
        `"${productName}: Reimagining ${keywords}."`,
        `"Simply ${productName}."`,
        `"Experience ${keywords} with ${productName}."`,
        `"${productName}. For those who love ${keywords}."`,
        `"The Future of ${keywords} is here: ${productName}."`,
        `"${productName}: Your ${keywords} Advantage."`,
        `"Think ${keywords}. Think ${productName}."`,
        `"${productName}. Driven by ${keywords}."`,
        `"Unlock your potential with ${productName}."`
    ];

    // Shuffle and pick 5
    const shuffled = templates.sort(() => 0.5 - Math.random());

    return `### Slogans for ${productName}\n\n` + shuffled.slice(0, 5).join('\n\n');
};
