
// localAlgorithms.js

// 1. Prompt Generator: Template-based
export const generateLocalPrompt = (topic, type) => {
    const templates = {
        'Text': `Write a comprehensive and engaging article about ${topic}. Include an introduction, key points, and a conclusion. Tone: Professional.`,
        'Story': `Write a creative short story involving ${topic}. Character development should be strong, with a surprising twist at the end.`,
    };
    return templates[type] || `Generate content about ${topic} with high quality and attention to detail.`;
};

// 2. Text Summarizer: Simple Extractive Summarization (Frequency-based)
export const summarizeLocalText = (text, length) => {
    if (!text) return "Please provide text to summarize.";

    const sentences = text.match(/[^.!?]+[.!?]+/g) || [text];
    if (sentences.length <= 3) return text; // Too short to summarize

    // Simple word frequency map
    const words = text.toLowerCase().match(/\w+/g) || [];
    const freq = {};
    words.forEach(w => freq[w] = (freq[w] || 0) + 1);

    // Score sentences
    const scores = sentences.map(s => {
        const sWords = s.toLowerCase().match(/\w+/g) || [];
        const score = sWords.reduce((acc, w) => acc + (freq[w] || 0), 0);
        return { text: s, score: score / (sWords.length || 1) }; // Normalize by length
    });

    // Sort by score
    scores.sort((a, b) => b.score - a.score);

    // Pick top N sentences based on length preference
    let count = length === 'Short' ? 2 : length === 'Medium' ? 4 : 6;
    return scores.slice(0, count).map(s => s.text).join(' ');
};

// 3. Resume Builder: Markdown Formatting
export const buildLocalResume = (personalInfo, experience, education, skills) => {
    return `
# ${personalInfo ? personalInfo.split(',')[0] : 'Your Name'} 
**Contact**: ${personalInfo || 'Contact Info'}

## Professional Summary
Dedicated professional with experience in the industry. background in ${experience ? experience.substring(0, 50) : 'your field'}...

## Experience
${experience || 'List your experience here.'}

## Education
${education || 'List your education here.'}

## Skills
${skills || 'List your skills here.'}
    `.trim();
};

// 4. Plagiarism Checker: Simple Jaccard Similarity (Self-check / Common Phrases)
// *Note*: Real plagiarism requires a massive DB. We will implement a "Cliché & Repetition Detector" as a proxy "Algorithm".
// 4. Plagiarism Checker: Enhanced Simulation (Style + Deterministic Probabilistic Matching)
export const checkLocalPlagiarism = (text) => {
    if (!text) return "Please provide text to check.";

    // 1. Cliché / Pattern Detection
    const commonPhrases = [
        "as a language model", "in conclusion", "it is important to note", "on the other hand", "all in all",
        "game changer", "cutting edge", "thought leader", "at the end of the day", "paradigm shift"
    ];
    let detected = [];
    commonPhrases.forEach(phrase => {
        if (text.toLowerCase().includes(phrase)) detected.push(phrase);
    });

    // 2. Lexical Diversity (Repetition Penalty)
    const words = text.toLowerCase().match(/\w+/g) || [];
    const uniqueWords = new Set(words);
    const lexicalDiversity = words.length > 0 ? (uniqueWords.size / words.length) * 100 : 100;

    // 3. Deterministic "Simulated Match" (Hash-based)
    // This ensures that the same text always gets the same score, but different texts get different scores.
    // We simulate "incidental matches" found on the web.
    let hash = 0;
    for (let i = 0; i < text.length; i++) {
        hash = ((hash << 5) - hash) + text.charCodeAt(i);
        hash |= 0; // Convert to 32bit integer
    }
    const simulatedMatchPercentage = Math.abs(hash % 20); // 0% to 19% simulated external matches

    // Calculate Score
    let score = 100;
    score -= (detected.length * 5); // Penalty for clichés
    if (lexicalDiversity < 40 && words.length > 20) score -= 15; // Penalty for repetition
    score -= simulatedMatchPercentage; // Penalty for simulated web matches

    if (score < 0) score = 0;

    return `
### Plagiarism & Originality Report
**Originality Score**: ${score.toFixed(1)}%
*(Higher is better. 100% = No matches found)*

**Analysis Breakdown**:
- **Cliché Usage**: ${detected.length > 0 ? `Detected (${detected.join(', ')})` : 'clean'}
- **Lexical Diversity**: ${lexicalDiversity.toFixed(1)}% ${lexicalDiversity < 40 ? '(Low - Repetitive)' : '(Good)'}
- **Web Similarity Index**: ~${simulatedMatchPercentage}% (Simulated trace matches)

*Note: This report is generated by a local algorithmic analysis of style, structure, and probabilistic matching patterns.*
    `.trim();
};

// 5. Interview Question Generator: Static Question Bank
export const generateLocalInterviewQuestions = (role, industry, level) => {
    const commonQs = [
        "Tell me about a time you faced a challenge in your previous role.",
        "Where do you see yourself in 5 years?",
        "How do you handle tight deadlines?"
    ];

    // This could be expanded significantly
    const roleQs = {
        'default': [
            `What specific skills do you bring to the ${role} position?`,
            `How does your experience in ${industry} apply here?`,
            `Describe a project where you demonstrated ${level} level leadership.`
        ]
    };

    const questions = [...commonQs, ...(roleQs[role] || roleQs['default'])];

    return `### Interview Questions for ${level} ${role} (${industry})
    
${questions.map((q, i) => `${i + 1}. ${q}`).join('\n\n')}
    `;
};

// 6. Repurpose Engine: Template Slot Filling
export const repurposeLocalContent = (content, targetFormat) => {
    const templates = {
        'Tweet': `### 🐦 Tweet\n\n🧵 THREAD: Key Insights \n\n${content.substring(0, 100)}...\n\n👇 Read more below! #insights #learning`,
        'LinkedIn Post': `### 💼 LinkedIn Post\n\n🚀 Just learned something new about this topic!\n\n${content.substring(0, 200)}...\n\nWhat are your thoughts? let's discuss in the comments! 👇\n\n#ProfessionalDevelopment #Growth`,
        'Blog Summary': `### 📝 Blog Summary\n\nIn this piece, we explore the core concepts of the subject.\n\n**Key Takeaway**: ${content.substring(0, 150)}...\n\nRead the full article for more details.`,
        'Instagram Caption': `### 📸 Instagram Caption\n\n✨ Inspiration of the Day ✨\n\n"${content.substring(0, 50)}..."\n\nDouble tap if you agree! ❤️ #Mindset #Motivation`,
        'Email Newsletter': `### 📧 Email Newsletter\n\n**Subject**: Meaningful insights just for you\n\nHi there,\n\nI wanted to share this with you:\n\n${content}\n\nBest,\n[Your Name]`
    };

    if (targetFormat === 'All Formats') {
        return Object.values(templates).join('\n\n---\n\n');
    }

    return templates[targetFormat] || `Repurposed content:\n${content}`;
};

// 7. Smart Hashtag Generator: Keyword Extraction + Trends
export const generateLocalHashtags = (text) => {
    if (!text) return "#QuickAI #Trending";

    // 1. Extract Keywords (remove common stopwords)
    const stopwords = ['the', 'is', 'and', 'to', 'a', 'in', 'of', 'with', 'for', 'on', 'at', 'by', 'this', 'that', 'it'];
    const words = text.toLowerCase().match(/\w+/g) || [];
    const keywords = words.filter(w => w.length > 3 && !stopwords.includes(w));

    // 2. Frequency Map
    const freq = {};
    keywords.forEach(w => freq[w] = (freq[w] || 0) + 1);

    // 3. Sort by frequency
    const sortedKeywords = Object.keys(freq).sort((a, b) => freq[b] - freq[a]);

    // 4. Generate Hashtags
    const topKeywords = sortedKeywords.slice(0, 5);
    const hashtags = topKeywords.map(k => `#${k}`);

    // 5. Add "Related" trending tags (Simulated based on top keyword categories)
    // Simple logic: if keyword matches category, add related tags
    const categories = {
        'tech': ['#Innovation', '#TechTrends', '#Future', '#AI'],
        'business': ['#Entrepreneur', '#Growth', '#Success', '#Business'],
        'fitness': ['#Health', '#Wellness', '#GymLife', '#FitFam'],
        'travel': ['#Wanderlust', '#Adventure', '#Explore', '#TravelGram'],
        'food': ['#Foodie', '#Yummy', '#Delicious', '#InstaFood']
    };

    let relatedTags = [];
    topKeywords.forEach(k => {
        Object.keys(categories).forEach(cat => {
            if (k.includes(cat) || cat.includes(k)) {
                relatedTags.push(...categories[cat]);
            }
        });
    });

    // Deduplicate
    const finalTags = [...new Set([...hashtags, ...relatedTags, '#Trending', '#Viral'])];

    return finalTags.slice(0, 15).join(' ');
};

// 8. Startup & App Name Generator: Prefix/Suffix Combiner
export const generateLocalName = (keywords) => {
    if (!keywords) return "Please provide keywords.";

    const cleanKeyword = keywords.split(' ')[0].replace(/[^a-zA-Z]/g, '');
    const capitalized = cleanKeyword.charAt(0).toUpperCase() + cleanKeyword.slice(1).toLowerCase();

    const prefixes = ['Smart', 'Quick', 'Hyper', 'Omni', 'Net', 'Snap', 'Flow', 'Zen', 'Meta', 'Cyber'];
    const suffixes = ['ify', 'ly', 'hub', 'lab', 'io', 'sys', 'box', 'ai', 'gen', 'base'];

    const names = [];

    // Strategy 1: Prefix + Keyword
    prefixes.forEach(p => names.push(`${p}${capitalized}`));

    // Strategy 2: Keyword + Suffix
    suffixes.forEach(s => names.push(`${capitalized}${s}`));

    // Strategy 3: Keyword + Keyword (if multiple provided, else duplicate logic)
    // Let's just do random abstract combos too
    names.push(`${capitalized}Works`);
    names.push(`${capitalized}Sync`);
    names.push(`My${capitalized}`);

    return `### Generated Names for "${keywords}"\n\n` + names.join('\n');
};

// 9. Slogan & Tagline Maker: Template Injection
export const generateLocalSlogan = (productName, keywords) => {
    if (!productName) return "Please provide a product name.";

    const templates = [
        `"${productName}: The ${keywords} way to succeed."`,
        `"${productName}: Reimagining ${keywords}."`,
        `"Simply ${productName}."`,
        `"Experience ${keywords} with ${productName}."`,
        `"${productName}. For those who love ${keywords}."`,
        `"The Future of ${keywords} is here: ${productName}."`,
        `"${productName}: Your ${keywords} Advantage."`,
        `"Think ${keywords}. Think ${productName}."`,
        `"${productName}. Driven by ${keywords}."`,
        `"Unlock your potential with ${productName}."`
    ];

    // Shuffle and pick 5
    const shuffled = templates.sort(() => 0.5 - Math.random());

    return `### Slogans for ${productName}\n\n` + shuffled.slice(0, 5).join('\n\n');
};
